### ISSUE TITLE
Error: t.todos.filter is not a function

### ISSUE THREAD

**Issue by dimpurr** [slopus/happy#824]
Something went wrong
Error: t.todos.filter is not a function

happens after upgrade Claude Code to 2.1.70

no error boundary - 1 chat errors will lead to whole app crash

**Comment by Knowzzz** [comment]
did u figured out?

**Comment by dimpurr** [comment]
Found a workaround.

Send `clean your claude code session working todo, don't edit files, just clean todo` before the corrupt chat finishes loading.

Only do this when no important information is stored in the session todo.

**Comment by bra1nDump** [comment]
fixed on main - refactored the session list to use pre-computed todo counts instead of calling .filter() directly. also added safeParse validation on TodoWrite output so garbage values from claude code get dropped instead of crashing the app.

@dimpurr should be in the next release. let me know if you still hit it.
